server:
  port: 8082

spring:
#  application:
#    name: QUESTION-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rahul
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8084

# logging settings

logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'

  level:
    root: info
    com.example: debug
    org.springframework: warn
  file:
    name: logs/question-service.log

  logback:
    rollingpolicy:
      max-history: 25
      max-file-size: 10MB
